---
- hosts: sample_platform_4
  remote_user: root
  tasks:
    - name: Generate an OpenSSL private key.
      when: provider == "self_signed" and task == "generate"
      openssl_privatekey:
        path: '{{ key_path }}'
    - name: Generate an OpenSSL CSR.
      when: provider == "self_signed" and task == "generate"
      openssl_csr:
        path: '{{ cert_path }}.csr'
        privatekey_path: '{{ key_path }}'
        common_name: "{{ server_hostname }}"
    - name: Generate a Self Signed OpenSSL certificate
      when: provider == "self_signed" and task == "generate"
      openssl_certificate:
        path: '{{ cert_path }}'
        privatekey_path: '{{ key_path }}'
        csr_path: '{{ cert_path }}.csr'
        provider: selfsigned
    - import_tasks: ssl_cert_with_acme-tiny.yaml
      when: provider == "lets_encrypt"
      vars:
        acme_private_key: '{{ ssl_key }}'
